name: Release
on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-*"
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
      - name: Build project assets
        id: make_assets
        run: |
          zip -r -9 user_api.zip lua README.md LICENSE
          tar cvJf user_api.tar.xz lua README.md LICENSE
          sha512sum user_api.zip user_api.tar.xz > sha512sums.txt
      - name: Get Release
        id: get_current_release
        uses: joutvhu/get-release@v1.0.3
        with:
          latest: true
          prerelease: true
          pattern: '^v.*'
          debug: true
          throwing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Release File
        id: release_txt
        run: echo ${{ github.sha }} > Release.txt
      - name: Test Release
        id: release_print
        run: cat Release.txt
      - name: Release
        id: release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            Release.txt
            user_api.tar.xz
            user_api.zip
            sha512sums.txt
          token: ${{ secrets.GITHUB_TOKEN }}
